on:
  push:
    tags:
    - 'v*'
name: Publish
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: egordm/gha-yarn-node-cache@v1
    - run: yarn install
    - run: yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: egordm/gha-yarn-node-cache@v1
    - name: Build
      run: yarn build
    - run: npm config set registry https://registry.npmjs.org/https://registry.npmjs.org/
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: example

